services:
  app:
    build: app
    volumes:
      - ./app:/app
      - todo-application-backend-app-data:/app/tmp
    ports:
      - "${EXPOSE_PORT}:8080"
    environment:
      - GOPROXY=${GOPROXY}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - todo-application-backend-network
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - todo-application-backend-app-postgres-data:/var/lib/postgresql/data
    networks:
      - todo-application-backend-network
    ports:
      - "${EXPOSE_POSTGRES_PORT}:5432"

networks:
  todo-application-backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.1.0/24

volumes:
  todo-application-backend-app-data:
  todo-application-backend-app-postgres-data:
